### ISSUE TITLE
multiple cookies with name, 'mxd-bbe-session' exception

### ISSUE THREAD

**Issue by andiMenge** [frankr612/plugin.video.maxdome#1]
Hi,

thank you for developing this addon. Unfortunately its not running on my machine because of this:

OS: 17.0-BETA4 Git:cf08208 Platform: Linux ARM 32-bit - Libreelec
```
18:34:58 1404.439209 T:1873802144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.cookies.CookieConflictError'>
                                            Error Contents: There are multiple cookies with name, 'mxd-bbe-session'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.maxdome/default.py", line 20, in <module>
                                                mas = maxdome.MaxdomeSession(username, password, cookie_path, region)
                                              File "/storage/.kodi/addons/plugin.video.maxdome/maxdome.py", line 64, in __init__
                                                self.Assets = MaxdomeAssets(self)
                                              File "/storage/.kodi/addons/plugin.video.maxdome/maxdome.py", line 116, in __init__
                                                self.api_headers['mxd-session'] = self.session.session.cookies['mxd-bbe-session']
                                              File "/storage/.kodi/addons/script.module.requests-gotham/lib/requests/cookies.py", line 329, in __getitem__
                                                return self._find_no_duplicates(name)
                                              File "/storage/.kodi/addons/script.module.requests-gotham/lib/requests/cookies.py", line 395, in _find_no_duplicates
                                                raise CookieConflictError('There are multiple cookies with name, %r' % (name))
                                            CookieConflictError: There are multiple cookies with name, 'mxd-bbe-session'
                                            -->End of Python script error report<--
```

I tried removing `/.kodi/userdata/addon_data/plugin.video.maxdome/COOKIES` but it has no effect.

Do you have any idea how to fix this?

TY!

**Comment by asciidisco** [comment]
Same here with a fresh install on OSX.

**Comment by asciidisco** [comment]
@andiMenge I got rid of this error by just (manually) deleting the the maxdome plugin as well as the requests plugin & reinstalling maxdome. It seemed that, for some reason, a non valid requests version ended up on my system somehow.

**Comment by andiMenge** [comment]
hey @asciidisco thanks for the tip. Unfortunately this didn't work on my setup.
I removed the following files and reinstalled the plugin:

`~/.kodi/userdata/addon_data/plugin.video.maxdome`
`~/.kodi/addons/plugin.video.maxdome`
`~/.kodi/addons/script.module.requests`

Error is still the **same**.

**Comment by andiMenge** [comment]
I have changed the line `sS'mxd-bbe-session'` to `sS'mxd-bbe-session2'` in the following file:

`.kodi/userdata/addon_data/plugin.video.maxdome/COOKIES`

this gets rid of the error `CookieConflictError: There are multiple cookies with name, 'mxd-bbe-session'`. But I didn't get something to play on my pi2

```
VideoPlayer: Opening: http://damxdcfuspo10.maxdome.de/1007836358-822338468-bcca4/piff-production/content/129/2/3headedshark_12902048_2015/3headedshark_12902048_2015_uspo1080muxd.ism/.mpd?1007836358-822338468-bcca4-eccs&c3.ri=3773326871076492624
13:53:38.501 T:1962361968 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:53:38.559 T:1443885984  NOTICE: Creating InputStream
13:53:38.847 T:1443885984  NOTICE: Creating Demuxer
13:53:39.161 T:1443885984   ERROR: Open - error probing input format, http://damxdcfuspo10.maxdome.de/1007836358-822338468-bcca4/piff-production/content/129/2/3headedshark_12902048_2015/3headedshark_12902048_2015_uspo1080muxd.ism/.mpd?1007836358-822338468-bcca4-eccs&c3.ri=3773326871076492624
13:53:39.162 T:1443885984   ERROR: OpenDemuxStream - Error creating demuxer
13:53:39.162 T:1443885984  NOTICE: CVideoPlayer::OnExit()
13:53:39.181 T:1962361968   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.maxdome/?action=play&id=12540150]
13:53:39.210 T:1962361968  NOTICE: CVideoPlayer::CloseFile()
13:53:39.210 T:1962361968  NOTICE: VideoPlayer: waiting for threads to exit
13:53:39.210 T:1962361968  NOTICE: VideoPlayer: finished waiting
13:53:39.211 T:1962361968  NOTICE: CVideoPlayer::CloseFile()
13:53:39.211 T:1962361968  NOTICE: VideoPlayer: waiting for threads to exit
13:53:39.211 T:1962361968  NOTICE: VideoPlayer: finished waiting
```
